###########
# site.title

title:    'BLOGGUE'
subtitle: 'Another Minimalistic Static Site Quick Starter Theme'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
